Repository BLACC-Smith/blacc-smith, pull requests merged in 2020-11, with the labels that each got.

#5 Automating Weekly Affirmations
  functions/affirmations/affirmations.js
  functions/affirmations/index.js
  functions/config.js
  functions/constants.js
  functions/index.js
  functions/utilities.js
Labels: Do not merge, Work in progress

#8 Update dailycc config
  functions/constants.js
  functions/dailyCC/constants.js
  functions/dailyCC/dailyCC.js
  functions/index.js
  functions/utilities.js
Labels: enhancement

#11 Implemented Asking for a Friend
  functions/afaf/afaf.js
  functions/afaf/index.js
  functions/config.js
  functions/constants.js
  functions/index.js
Labels: Feature, enhancement

#25 Restructured codebase + scheduled jobs
  functions/afaf/afaf.js
  functions/affirmations/affirmations.js
  functions/config.js
  functions/constants.js
  functions/endpoints/affirmations/affirmations.js
  functions/endpoints/affirmations/index.js
  functions/endpoints/dailyCC/constants.js
  functions/endpoints/dailyCC/dailyCC.js
  functions/endpoints/dailyCC/index.js
  functions/endpoints/endpointHandler.js
  functions/endpoints/endpointUtilities.js
  functions/endpoints/index.js
  functions/endpoints/middleware.js
  functions/index.js
  functions/listeners/afaf/afaf.js
  functions/listeners/afaf/index.js
  functions/listeners/config.js
  functions/listeners/discordListener.js
  functions/listeners/index.js
  functions/package.json
  functions/utilities.js
Labels: enhancement
